// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: votesystem/identity/query.proto

package types

import (
	context "context"
	fmt "fmt"
	query "github.com/cosmos/cosmos-sdk/types/query"
	_ "github.com/cosmos/gogoproto/gogoproto"
	grpc1 "github.com/cosmos/gogoproto/grpc"
	proto "github.com/cosmos/gogoproto/proto"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	io "io"
	math "math"
	math_bits "math/bits"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

// QueryParamsRequest is request type for the Query/Params RPC method.
type QueryParamsRequest struct {
}

func (m *QueryParamsRequest) Reset()         { *m = QueryParamsRequest{} }
func (m *QueryParamsRequest) String() string { return proto.CompactTextString(m) }
func (*QueryParamsRequest) ProtoMessage()    {}
func (*QueryParamsRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_16fc533c887e157e, []int{0}
}
func (m *QueryParamsRequest) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryParamsRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryParamsRequest.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryParamsRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryParamsRequest.Merge(m, src)
}
func (m *QueryParamsRequest) XXX_Size() int {
	return m.Size()
}
func (m *QueryParamsRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryParamsRequest.DiscardUnknown(m)
}

var xxx_messageInfo_QueryParamsRequest proto.InternalMessageInfo

// QueryParamsResponse is response type for the Query/Params RPC method.
type QueryParamsResponse struct {
	// params holds all the parameters of this module.
	Params Params `protobuf:"bytes,1,opt,name=params,proto3" json:"params"`
}

func (m *QueryParamsResponse) Reset()         { *m = QueryParamsResponse{} }
func (m *QueryParamsResponse) String() string { return proto.CompactTextString(m) }
func (*QueryParamsResponse) ProtoMessage()    {}
func (*QueryParamsResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_16fc533c887e157e, []int{1}
}
func (m *QueryParamsResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryParamsResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryParamsResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryParamsResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryParamsResponse.Merge(m, src)
}
func (m *QueryParamsResponse) XXX_Size() int {
	return m.Size()
}
func (m *QueryParamsResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryParamsResponse.DiscardUnknown(m)
}

var xxx_messageInfo_QueryParamsResponse proto.InternalMessageInfo

func (m *QueryParamsResponse) GetParams() Params {
	if m != nil {
		return m.Params
	}
	return Params{}
}

type QueryGetRegisteredVoterRequest struct {
	Id uint64 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
}

func (m *QueryGetRegisteredVoterRequest) Reset()         { *m = QueryGetRegisteredVoterRequest{} }
func (m *QueryGetRegisteredVoterRequest) String() string { return proto.CompactTextString(m) }
func (*QueryGetRegisteredVoterRequest) ProtoMessage()    {}
func (*QueryGetRegisteredVoterRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_16fc533c887e157e, []int{2}
}
func (m *QueryGetRegisteredVoterRequest) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryGetRegisteredVoterRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryGetRegisteredVoterRequest.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryGetRegisteredVoterRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryGetRegisteredVoterRequest.Merge(m, src)
}
func (m *QueryGetRegisteredVoterRequest) XXX_Size() int {
	return m.Size()
}
func (m *QueryGetRegisteredVoterRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryGetRegisteredVoterRequest.DiscardUnknown(m)
}

var xxx_messageInfo_QueryGetRegisteredVoterRequest proto.InternalMessageInfo

func (m *QueryGetRegisteredVoterRequest) GetId() uint64 {
	if m != nil {
		return m.Id
	}
	return 0
}

type QueryGetRegisteredVoterResponse struct {
	RegisteredVoter RegisteredVoter `protobuf:"bytes,1,opt,name=RegisteredVoter,proto3" json:"RegisteredVoter"`
}

func (m *QueryGetRegisteredVoterResponse) Reset()         { *m = QueryGetRegisteredVoterResponse{} }
func (m *QueryGetRegisteredVoterResponse) String() string { return proto.CompactTextString(m) }
func (*QueryGetRegisteredVoterResponse) ProtoMessage()    {}
func (*QueryGetRegisteredVoterResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_16fc533c887e157e, []int{3}
}
func (m *QueryGetRegisteredVoterResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryGetRegisteredVoterResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryGetRegisteredVoterResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryGetRegisteredVoterResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryGetRegisteredVoterResponse.Merge(m, src)
}
func (m *QueryGetRegisteredVoterResponse) XXX_Size() int {
	return m.Size()
}
func (m *QueryGetRegisteredVoterResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryGetRegisteredVoterResponse.DiscardUnknown(m)
}

var xxx_messageInfo_QueryGetRegisteredVoterResponse proto.InternalMessageInfo

func (m *QueryGetRegisteredVoterResponse) GetRegisteredVoter() RegisteredVoter {
	if m != nil {
		return m.RegisteredVoter
	}
	return RegisteredVoter{}
}

type QueryAllRegisteredVoterRequest struct {
	Pagination *query.PageRequest `protobuf:"bytes,1,opt,name=pagination,proto3" json:"pagination,omitempty"`
}

func (m *QueryAllRegisteredVoterRequest) Reset()         { *m = QueryAllRegisteredVoterRequest{} }
func (m *QueryAllRegisteredVoterRequest) String() string { return proto.CompactTextString(m) }
func (*QueryAllRegisteredVoterRequest) ProtoMessage()    {}
func (*QueryAllRegisteredVoterRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_16fc533c887e157e, []int{4}
}
func (m *QueryAllRegisteredVoterRequest) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryAllRegisteredVoterRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryAllRegisteredVoterRequest.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryAllRegisteredVoterRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryAllRegisteredVoterRequest.Merge(m, src)
}
func (m *QueryAllRegisteredVoterRequest) XXX_Size() int {
	return m.Size()
}
func (m *QueryAllRegisteredVoterRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryAllRegisteredVoterRequest.DiscardUnknown(m)
}

var xxx_messageInfo_QueryAllRegisteredVoterRequest proto.InternalMessageInfo

func (m *QueryAllRegisteredVoterRequest) GetPagination() *query.PageRequest {
	if m != nil {
		return m.Pagination
	}
	return nil
}

type QueryAllRegisteredVoterResponse struct {
	RegisteredVoter []RegisteredVoter   `protobuf:"bytes,1,rep,name=RegisteredVoter,proto3" json:"RegisteredVoter"`
	Pagination      *query.PageResponse `protobuf:"bytes,2,opt,name=pagination,proto3" json:"pagination,omitempty"`
}

func (m *QueryAllRegisteredVoterResponse) Reset()         { *m = QueryAllRegisteredVoterResponse{} }
func (m *QueryAllRegisteredVoterResponse) String() string { return proto.CompactTextString(m) }
func (*QueryAllRegisteredVoterResponse) ProtoMessage()    {}
func (*QueryAllRegisteredVoterResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_16fc533c887e157e, []int{5}
}
func (m *QueryAllRegisteredVoterResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryAllRegisteredVoterResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryAllRegisteredVoterResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryAllRegisteredVoterResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryAllRegisteredVoterResponse.Merge(m, src)
}
func (m *QueryAllRegisteredVoterResponse) XXX_Size() int {
	return m.Size()
}
func (m *QueryAllRegisteredVoterResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryAllRegisteredVoterResponse.DiscardUnknown(m)
}

var xxx_messageInfo_QueryAllRegisteredVoterResponse proto.InternalMessageInfo

func (m *QueryAllRegisteredVoterResponse) GetRegisteredVoter() []RegisteredVoter {
	if m != nil {
		return m.RegisteredVoter
	}
	return nil
}

func (m *QueryAllRegisteredVoterResponse) GetPagination() *query.PageResponse {
	if m != nil {
		return m.Pagination
	}
	return nil
}

type QueryGetVoterStatusRequest struct {
	VoterAddress string `protobuf:"bytes,1,opt,name=voterAddress,proto3" json:"voterAddress,omitempty"`
}

func (m *QueryGetVoterStatusRequest) Reset()         { *m = QueryGetVoterStatusRequest{} }
func (m *QueryGetVoterStatusRequest) String() string { return proto.CompactTextString(m) }
func (*QueryGetVoterStatusRequest) ProtoMessage()    {}
func (*QueryGetVoterStatusRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_16fc533c887e157e, []int{6}
}
func (m *QueryGetVoterStatusRequest) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryGetVoterStatusRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryGetVoterStatusRequest.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryGetVoterStatusRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryGetVoterStatusRequest.Merge(m, src)
}
func (m *QueryGetVoterStatusRequest) XXX_Size() int {
	return m.Size()
}
func (m *QueryGetVoterStatusRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryGetVoterStatusRequest.DiscardUnknown(m)
}

var xxx_messageInfo_QueryGetVoterStatusRequest proto.InternalMessageInfo

func (m *QueryGetVoterStatusRequest) GetVoterAddress() string {
	if m != nil {
		return m.VoterAddress
	}
	return ""
}

type QueryGetVoterStatusResponse struct {
	IsRegistered      bool   `protobuf:"varint,1,opt,name=is_registered,json=isRegistered,proto3" json:"is_registered,omitempty"`
	IdentityProofHash string `protobuf:"bytes,2,opt,name=identity_proof_hash,json=identityProofHash,proto3" json:"identity_proof_hash,omitempty"`
}

func (m *QueryGetVoterStatusResponse) Reset()         { *m = QueryGetVoterStatusResponse{} }
func (m *QueryGetVoterStatusResponse) String() string { return proto.CompactTextString(m) }
func (*QueryGetVoterStatusResponse) ProtoMessage()    {}
func (*QueryGetVoterStatusResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_16fc533c887e157e, []int{7}
}
func (m *QueryGetVoterStatusResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryGetVoterStatusResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryGetVoterStatusResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryGetVoterStatusResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryGetVoterStatusResponse.Merge(m, src)
}
func (m *QueryGetVoterStatusResponse) XXX_Size() int {
	return m.Size()
}
func (m *QueryGetVoterStatusResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryGetVoterStatusResponse.DiscardUnknown(m)
}

var xxx_messageInfo_QueryGetVoterStatusResponse proto.InternalMessageInfo

func (m *QueryGetVoterStatusResponse) GetIsRegistered() bool {
	if m != nil {
		return m.IsRegistered
	}
	return false
}

func (m *QueryGetVoterStatusResponse) GetIdentityProofHash() string {
	if m != nil {
		return m.IdentityProofHash
	}
	return ""
}

func init() {
	proto.RegisterType((*QueryParamsRequest)(nil), "votesystem.identity.QueryParamsRequest")
	proto.RegisterType((*QueryParamsResponse)(nil), "votesystem.identity.QueryParamsResponse")
	proto.RegisterType((*QueryGetRegisteredVoterRequest)(nil), "votesystem.identity.QueryGetRegisteredVoterRequest")
	proto.RegisterType((*QueryGetRegisteredVoterResponse)(nil), "votesystem.identity.QueryGetRegisteredVoterResponse")
	proto.RegisterType((*QueryAllRegisteredVoterRequest)(nil), "votesystem.identity.QueryAllRegisteredVoterRequest")
	proto.RegisterType((*QueryAllRegisteredVoterResponse)(nil), "votesystem.identity.QueryAllRegisteredVoterResponse")
	proto.RegisterType((*QueryGetVoterStatusRequest)(nil), "votesystem.identity.QueryGetVoterStatusRequest")
	proto.RegisterType((*QueryGetVoterStatusResponse)(nil), "votesystem.identity.QueryGetVoterStatusResponse")
}

func init() { proto.RegisterFile("votesystem/identity/query.proto", fileDescriptor_16fc533c887e157e) }

var fileDescriptor_16fc533c887e157e = []byte{
	// 616 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xa4, 0x94, 0xc1, 0x6e, 0xd3, 0x40,
	0x10, 0x86, 0xe3, 0xd0, 0x46, 0x74, 0x29, 0x45, 0x6c, 0x7a, 0x40, 0x0e, 0x38, 0x95, 0x0b, 0xa4,
	0xaa, 0xc0, 0xdb, 0xa6, 0x05, 0x09, 0x89, 0x03, 0xe9, 0x81, 0x72, 0x0c, 0x06, 0x71, 0xe0, 0x12,
	0x6d, 0xf0, 0xe2, 0xac, 0x94, 0x78, 0x5d, 0xef, 0xa6, 0x10, 0x55, 0x95, 0x10, 0x4f, 0x80, 0xc4,
	0x1b, 0xf0, 0x00, 0x08, 0xde, 0x80, 0x63, 0x8f, 0x95, 0xb8, 0x70, 0x42, 0x28, 0xe1, 0x41, 0x90,
	0x77, 0x37, 0x4d, 0x9c, 0xd8, 0x69, 0x50, 0x6f, 0x51, 0x66, 0xe6, 0x9f, 0xef, 0xdf, 0x99, 0x31,
	0x28, 0x1f, 0x32, 0x41, 0x78, 0x8f, 0x0b, 0xd2, 0x41, 0xd4, 0x23, 0x81, 0xa0, 0xa2, 0x87, 0x0e,
	0xba, 0x24, 0xea, 0x39, 0x61, 0xc4, 0x04, 0x83, 0xc5, 0x51, 0x82, 0x33, 0x4c, 0x30, 0x57, 0x7d,
	0xe6, 0x33, 0x19, 0x47, 0xf1, 0x2f, 0x95, 0x6a, 0xde, 0xf4, 0x19, 0xf3, 0xdb, 0x04, 0xe1, 0x90,
	0x22, 0x1c, 0x04, 0x4c, 0x60, 0x41, 0x59, 0xc0, 0x75, 0x74, 0xf3, 0x0d, 0xe3, 0x1d, 0xc6, 0x51,
	0x13, 0x73, 0xa2, 0x3a, 0xa0, 0xc3, 0xed, 0x26, 0x11, 0x78, 0x1b, 0x85, 0xd8, 0xa7, 0x81, 0x4c,
	0xd6, 0xb9, 0x6b, 0x69, 0x54, 0x21, 0x8e, 0x70, 0xe7, 0x4c, 0x2d, 0x2d, 0x23, 0x22, 0x3e, 0xe5,
	0x82, 0x44, 0xc4, 0x6b, 0xc4, 0xe1, 0x48, 0xe5, 0xda, 0xab, 0x00, 0x3e, 0x8f, 0xfb, 0xd5, 0xa5,
	0x80, 0x4b, 0x0e, 0xba, 0x84, 0x0b, 0xbb, 0x0e, 0x8a, 0x89, 0x7f, 0x79, 0xc8, 0x02, 0x4e, 0xe0,
	0x23, 0x50, 0x50, 0x8d, 0x6e, 0x18, 0x6b, 0xc6, 0xc6, 0x95, 0x6a, 0xc9, 0x49, 0x79, 0x00, 0x47,
	0x15, 0xed, 0x2d, 0x9c, 0xfc, 0x2e, 0xe7, 0x5c, 0x5d, 0x60, 0x6f, 0x01, 0x4b, 0x2a, 0xee, 0x13,
	0xe1, 0x9e, 0x91, 0xbc, 0x8a, 0x41, 0x74, 0x4f, 0xb8, 0x02, 0xf2, 0xd4, 0x93, 0xc2, 0x0b, 0x6e,
	0x9e, 0x7a, 0xf6, 0x3b, 0x50, 0xce, 0xac, 0xd0, 0x3c, 0x2f, 0xc1, 0xb5, 0x89, 0x90, 0x06, 0xbb,
	0x9d, 0x0a, 0x36, 0x91, 0xab, 0x09, 0x27, 0x25, 0xec, 0x96, 0x46, 0xad, 0xb5, 0xdb, 0x19, 0xa8,
	0x4f, 0x01, 0x18, 0x8d, 0x45, 0xb7, 0xbc, 0xeb, 0xa8, 0x19, 0x3a, 0xf1, 0x0c, 0x1d, 0xb5, 0x25,
	0x7a, 0x86, 0x4e, 0x1d, 0xfb, 0x44, 0xd7, 0xba, 0x63, 0x95, 0xf6, 0x0f, 0x43, 0x7b, 0x4c, 0x6b,
	0x35, 0xcb, 0xe3, 0xa5, 0x0b, 0x7a, 0x84, 0xfb, 0x09, 0x07, 0x79, 0xe9, 0xa0, 0x72, 0xae, 0x03,
	0x85, 0x94, 0xb0, 0xf0, 0x04, 0x98, 0xc3, 0x29, 0x49, 0xe5, 0x17, 0x02, 0x8b, 0xee, 0x70, 0x8f,
	0xa0, 0x0d, 0x96, 0xe5, 0xb2, 0xd5, 0x3c, 0x2f, 0x22, 0x5c, 0xad, 0xcd, 0x92, 0x9b, 0xf8, 0xcf,
	0x8e, 0x40, 0x29, 0x55, 0x41, 0xfb, 0x5f, 0x07, 0x57, 0x29, 0x6f, 0x8c, 0xb6, 0x57, 0x6a, 0x5c,
	0x76, 0x97, 0x29, 0x1f, 0x79, 0x82, 0x0e, 0x28, 0x0e, 0x5f, 0xa0, 0x11, 0x46, 0x8c, 0xbd, 0x6d,
	0xb4, 0x30, 0x6f, 0x49, 0x5f, 0x4b, 0xee, 0xf5, 0x61, 0xa8, 0x1e, 0x47, 0x9e, 0x61, 0xde, 0xaa,
	0x7e, 0x59, 0x04, 0x8b, 0xb2, 0x29, 0xfc, 0x60, 0x80, 0x82, 0x5a, 0x58, 0x58, 0x49, 0x7d, 0xd0,
	0xe9, 0xeb, 0x30, 0x37, 0xce, 0x4f, 0x54, 0xf0, 0xf6, 0xfa, 0xc7, 0x9f, 0x7f, 0x3f, 0xe7, 0x6f,
	0xc1, 0x12, 0xca, 0x3e, 0x5a, 0xf8, 0xcd, 0x98, 0x1a, 0x31, 0xdc, 0xc9, 0x6e, 0x91, 0x79, 0x41,
	0xe6, 0xee, 0xff, 0x15, 0x69, 0xc6, 0xaa, 0x64, 0xbc, 0x07, 0x37, 0xd1, 0x3c, 0x9f, 0x0d, 0x74,
	0x44, 0xbd, 0x63, 0xf8, 0xd5, 0x00, 0x70, 0x42, 0xaf, 0xd6, 0x6e, 0xcf, 0xa2, 0xce, 0x3c, 0xa6,
	0x59, 0xd4, 0xd9, 0x67, 0x61, 0xdf, 0x97, 0xd4, 0x15, 0x78, 0x67, 0x2e, 0x6a, 0xf8, 0xdd, 0x00,
	0x2b, 0xc9, 0x05, 0x83, 0x68, 0xe6, 0x6b, 0x4d, 0x2f, 0xb3, 0xb9, 0x35, 0x7f, 0x81, 0x86, 0x7c,
	0x2c, 0x21, 0x1f, 0xc2, 0xdd, 0x54, 0x48, 0x9f, 0x08, 0x45, 0xd7, 0xe0, 0xb2, 0x0c, 0x1d, 0x8d,
	0xdf, 0xc5, 0xf1, 0xde, 0x83, 0x93, 0xbe, 0x65, 0x9c, 0xf6, 0x2d, 0xe3, 0x4f, 0xdf, 0x32, 0x3e,
	0x0d, 0xac, 0xdc, 0xe9, 0xc0, 0xca, 0xfd, 0x1a, 0x58, 0xb9, 0xd7, 0xa5, 0x31, 0xb9, 0xf7, 0x23,
	0x41, 0xd1, 0x0b, 0x09, 0x6f, 0x16, 0xe4, 0x87, 0x7d, 0xe7, 0x5f, 0x00, 0x00, 0x00, 0xff, 0xff,
	0xc9, 0xcc, 0xad, 0xc1, 0xbe, 0x06, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// QueryClient is the client API for Query service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type QueryClient interface {
	// Parameters queries the parameters of the module.
	Params(ctx context.Context, in *QueryParamsRequest, opts ...grpc.CallOption) (*QueryParamsResponse, error)
	// Queries a list of RegisteredVoter items.
	RegisteredVoter(ctx context.Context, in *QueryGetRegisteredVoterRequest, opts ...grpc.CallOption) (*QueryGetRegisteredVoterResponse, error)
	RegisteredVoterAll(ctx context.Context, in *QueryAllRegisteredVoterRequest, opts ...grpc.CallOption) (*QueryAllRegisteredVoterResponse, error)
	// Queries a list of GetVoterStatus items.
	GetVoterStatus(ctx context.Context, in *QueryGetVoterStatusRequest, opts ...grpc.CallOption) (*QueryGetVoterStatusResponse, error)
}

type queryClient struct {
	cc grpc1.ClientConn
}

func NewQueryClient(cc grpc1.ClientConn) QueryClient {
	return &queryClient{cc}
}

func (c *queryClient) Params(ctx context.Context, in *QueryParamsRequest, opts ...grpc.CallOption) (*QueryParamsResponse, error) {
	out := new(QueryParamsResponse)
	err := c.cc.Invoke(ctx, "/votesystem.identity.Query/Params", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *queryClient) RegisteredVoter(ctx context.Context, in *QueryGetRegisteredVoterRequest, opts ...grpc.CallOption) (*QueryGetRegisteredVoterResponse, error) {
	out := new(QueryGetRegisteredVoterResponse)
	err := c.cc.Invoke(ctx, "/votesystem.identity.Query/RegisteredVoter", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *queryClient) RegisteredVoterAll(ctx context.Context, in *QueryAllRegisteredVoterRequest, opts ...grpc.CallOption) (*QueryAllRegisteredVoterResponse, error) {
	out := new(QueryAllRegisteredVoterResponse)
	err := c.cc.Invoke(ctx, "/votesystem.identity.Query/RegisteredVoterAll", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *queryClient) GetVoterStatus(ctx context.Context, in *QueryGetVoterStatusRequest, opts ...grpc.CallOption) (*QueryGetVoterStatusResponse, error) {
	out := new(QueryGetVoterStatusResponse)
	err := c.cc.Invoke(ctx, "/votesystem.identity.Query/GetVoterStatus", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// QueryServer is the server API for Query service.
type QueryServer interface {
	// Parameters queries the parameters of the module.
	Params(context.Context, *QueryParamsRequest) (*QueryParamsResponse, error)
	// Queries a list of RegisteredVoter items.
	RegisteredVoter(context.Context, *QueryGetRegisteredVoterRequest) (*QueryGetRegisteredVoterResponse, error)
	RegisteredVoterAll(context.Context, *QueryAllRegisteredVoterRequest) (*QueryAllRegisteredVoterResponse, error)
	// Queries a list of GetVoterStatus items.
	GetVoterStatus(context.Context, *QueryGetVoterStatusRequest) (*QueryGetVoterStatusResponse, error)
}

// UnimplementedQueryServer can be embedded to have forward compatible implementations.
type UnimplementedQueryServer struct {
}

func (*UnimplementedQueryServer) Params(ctx context.Context, req *QueryParamsRequest) (*QueryParamsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Params not implemented")
}
func (*UnimplementedQueryServer) RegisteredVoter(ctx context.Context, req *QueryGetRegisteredVoterRequest) (*QueryGetRegisteredVoterResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RegisteredVoter not implemented")
}
func (*UnimplementedQueryServer) RegisteredVoterAll(ctx context.Context, req *QueryAllRegisteredVoterRequest) (*QueryAllRegisteredVoterResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RegisteredVoterAll not implemented")
}
func (*UnimplementedQueryServer) GetVoterStatus(ctx context.Context, req *QueryGetVoterStatusRequest) (*QueryGetVoterStatusResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetVoterStatus not implemented")
}

func RegisterQueryServer(s grpc1.Server, srv QueryServer) {
	s.RegisterService(&_Query_serviceDesc, srv)
}

func _Query_Params_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryParamsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueryServer).Params(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/votesystem.identity.Query/Params",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueryServer).Params(ctx, req.(*QueryParamsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Query_RegisteredVoter_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryGetRegisteredVoterRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueryServer).RegisteredVoter(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/votesystem.identity.Query/RegisteredVoter",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueryServer).RegisteredVoter(ctx, req.(*QueryGetRegisteredVoterRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Query_RegisteredVoterAll_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryAllRegisteredVoterRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueryServer).RegisteredVoterAll(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/votesystem.identity.Query/RegisteredVoterAll",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueryServer).RegisteredVoterAll(ctx, req.(*QueryAllRegisteredVoterRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Query_GetVoterStatus_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryGetVoterStatusRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueryServer).GetVoterStatus(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/votesystem.identity.Query/GetVoterStatus",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueryServer).GetVoterStatus(ctx, req.(*QueryGetVoterStatusRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _Query_serviceDesc = grpc.ServiceDesc{
	ServiceName: "votesystem.identity.Query",
	HandlerType: (*QueryServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Params",
			Handler:    _Query_Params_Handler,
		},
		{
			MethodName: "RegisteredVoter",
			Handler:    _Query_RegisteredVoter_Handler,
		},
		{
			MethodName: "RegisteredVoterAll",
			Handler:    _Query_RegisteredVoterAll_Handler,
		},
		{
			MethodName: "GetVoterStatus",
			Handler:    _Query_GetVoterStatus_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "votesystem/identity/query.proto",
}

func (m *QueryParamsRequest) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryParamsRequest) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryParamsRequest) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	return len(dAtA) - i, nil
}

func (m *QueryParamsResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryParamsResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryParamsResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	{
		size, err := m.Params.MarshalToSizedBuffer(dAtA[:i])
		if err != nil {
			return 0, err
		}
		i -= size
		i = encodeVarintQuery(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0xa
	return len(dAtA) - i, nil
}

func (m *QueryGetRegisteredVoterRequest) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryGetRegisteredVoterRequest) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryGetRegisteredVoterRequest) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.Id != 0 {
		i = encodeVarintQuery(dAtA, i, uint64(m.Id))
		i--
		dAtA[i] = 0x8
	}
	return len(dAtA) - i, nil
}

func (m *QueryGetRegisteredVoterResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryGetRegisteredVoterResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryGetRegisteredVoterResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	{
		size, err := m.RegisteredVoter.MarshalToSizedBuffer(dAtA[:i])
		if err != nil {
			return 0, err
		}
		i -= size
		i = encodeVarintQuery(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0xa
	return len(dAtA) - i, nil
}

func (m *QueryAllRegisteredVoterRequest) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryAllRegisteredVoterRequest) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryAllRegisteredVoterRequest) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.Pagination != nil {
		{
			size, err := m.Pagination.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintQuery(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *QueryAllRegisteredVoterResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryAllRegisteredVoterResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryAllRegisteredVoterResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.Pagination != nil {
		{
			size, err := m.Pagination.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintQuery(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0x12
	}
	if len(m.RegisteredVoter) > 0 {
		for iNdEx := len(m.RegisteredVoter) - 1; iNdEx >= 0; iNdEx-- {
			{
				size, err := m.RegisteredVoter[iNdEx].MarshalToSizedBuffer(dAtA[:i])
				if err != nil {
					return 0, err
				}
				i -= size
				i = encodeVarintQuery(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0xa
		}
	}
	return len(dAtA) - i, nil
}

func (m *QueryGetVoterStatusRequest) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryGetVoterStatusRequest) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryGetVoterStatusRequest) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.VoterAddress) > 0 {
		i -= len(m.VoterAddress)
		copy(dAtA[i:], m.VoterAddress)
		i = encodeVarintQuery(dAtA, i, uint64(len(m.VoterAddress)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *QueryGetVoterStatusResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryGetVoterStatusResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryGetVoterStatusResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.IdentityProofHash) > 0 {
		i -= len(m.IdentityProofHash)
		copy(dAtA[i:], m.IdentityProofHash)
		i = encodeVarintQuery(dAtA, i, uint64(len(m.IdentityProofHash)))
		i--
		dAtA[i] = 0x12
	}
	if m.IsRegistered {
		i--
		if m.IsRegistered {
			dAtA[i] = 1
		} else {
			dAtA[i] = 0
		}
		i--
		dAtA[i] = 0x8
	}
	return len(dAtA) - i, nil
}

func encodeVarintQuery(dAtA []byte, offset int, v uint64) int {
	offset -= sovQuery(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *QueryParamsRequest) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	return n
}

func (m *QueryParamsResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = m.Params.Size()
	n += 1 + l + sovQuery(uint64(l))
	return n
}

func (m *QueryGetRegisteredVoterRequest) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.Id != 0 {
		n += 1 + sovQuery(uint64(m.Id))
	}
	return n
}

func (m *QueryGetRegisteredVoterResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = m.RegisteredVoter.Size()
	n += 1 + l + sovQuery(uint64(l))
	return n
}

func (m *QueryAllRegisteredVoterRequest) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.Pagination != nil {
		l = m.Pagination.Size()
		n += 1 + l + sovQuery(uint64(l))
	}
	return n
}

func (m *QueryAllRegisteredVoterResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if len(m.RegisteredVoter) > 0 {
		for _, e := range m.RegisteredVoter {
			l = e.Size()
			n += 1 + l + sovQuery(uint64(l))
		}
	}
	if m.Pagination != nil {
		l = m.Pagination.Size()
		n += 1 + l + sovQuery(uint64(l))
	}
	return n
}

func (m *QueryGetVoterStatusRequest) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.VoterAddress)
	if l > 0 {
		n += 1 + l + sovQuery(uint64(l))
	}
	return n
}

func (m *QueryGetVoterStatusResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.IsRegistered {
		n += 2
	}
	l = len(m.IdentityProofHash)
	if l > 0 {
		n += 1 + l + sovQuery(uint64(l))
	}
	return n
}

func sovQuery(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozQuery(x uint64) (n int) {
	return sovQuery(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *QueryParamsRequest) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryParamsRequest: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryParamsRequest: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryParamsResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryParamsResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryParamsResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Params", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.Params.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryGetRegisteredVoterRequest) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryGetRegisteredVoterRequest: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryGetRegisteredVoterRequest: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Id", wireType)
			}
			m.Id = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Id |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryGetRegisteredVoterResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryGetRegisteredVoterResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryGetRegisteredVoterResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field RegisteredVoter", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.RegisteredVoter.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryAllRegisteredVoterRequest) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryAllRegisteredVoterRequest: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryAllRegisteredVoterRequest: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Pagination", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.Pagination == nil {
				m.Pagination = &query.PageRequest{}
			}
			if err := m.Pagination.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryAllRegisteredVoterResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryAllRegisteredVoterResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryAllRegisteredVoterResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field RegisteredVoter", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.RegisteredVoter = append(m.RegisteredVoter, RegisteredVoter{})
			if err := m.RegisteredVoter[len(m.RegisteredVoter)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Pagination", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.Pagination == nil {
				m.Pagination = &query.PageResponse{}
			}
			if err := m.Pagination.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryGetVoterStatusRequest) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryGetVoterStatusRequest: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryGetVoterStatusRequest: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field VoterAddress", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.VoterAddress = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryGetVoterStatusResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryGetVoterStatusResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryGetVoterStatusResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field IsRegistered", wireType)
			}
			var v int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				v |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			m.IsRegistered = bool(v != 0)
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field IdentityProofHash", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.IdentityProofHash = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipQuery(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthQuery
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupQuery
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthQuery
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthQuery        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowQuery          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupQuery = fmt.Errorf("proto: unexpected end of group")
)
